# Generated by Django 4.0.5 on 2022-06-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formations',
            old_name='end',
            new_name='start_at',
        ),
        migrations.RemoveField(
            model_name='formations',
            name='start',
        ),
        migrations.AddField(
            model_name='experiences',
            name='end_at',
            field=models.DateField(blank=True, default='2020-02-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiences',
            name='etablisment_name',
            field=models.CharField(default='google', max_length=72),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiences',
            name='start_at',
            field=models.DateField(default='2021-05-06'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formations',
            name='end_at',
            field=models.DateField(blank=True, default='2019-04-10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiences',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='post',
            field=models.CharField(max_length=72),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='type',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='formations',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='formations',
            name='name',
            field=models.CharField(max_length=72),
        ),
    ]
